
name: CI

#workflow_dispatch:  # manual trigger
on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Choco version
        run: |
          choco --version
      
      - name: Choco Pack
        run: |
          choco pack -d

      - name: Run Pester Tests
        shell: pwsh
        run: |
          .\WinSecurityBaseline.Pester.ps1

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: ${{ github.workspace }}/**/*.xml

      - uses: actions/upload-artifact@v2
        with:
          name: choco-package
          path: ${{ github.workspace }}/
      
      - name: Archive Release
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ github.workspace }} -DestinationPath ${{ github.workspace }}\Release.zip
      
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}\Release.zip
          asset_name: Release.zip
          asset_content_type: application/zip

  # dev_deploy:
  #   needs: build
  #   runs-on: windows-latest
  #   environment:
  #     name: test
  #   steps:
  #     - name: Run a multi-line script
  #       run: |
  #         choco --version
