
name: CI

#workflow_dispatch:  # manual trigger
on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Output
        run: |
          write-output $GITHUB_WORKSPACE
          write-output $GITHUB_REPOSITORY
        shell: pwsh

      - name: Get Choco version
        run: |
          choco --version
      
      - name: Choco Pack
        run: |
          choco pack -d

      - name: Run Pester tests
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -Confirm:$false -Force
          Invoke-Pester
        shell: pwsh

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: $GITHUB_WORKSPACE/**/*.xml

      - uses: actions/upload-artifact@v2
        with:
          name: choco-package
          path: $GITHUB_WORKSPACE/

  # dev_deploy:
  #   needs: build
  #   runs-on: windows-latest
  #   environment:
  #     name: test
  #   steps:
  #     - name: Run a multi-line script
  #       run: |
  #         choco --version
